print("Basit hesap makinesi")
sayi1 = input("Toplama isleminde kullanilacak ilk sayi nedir? ")
sayi2 = input("Toplama isleminde kullanilacak ikinci sayi nedir? ")
toplam = int(sayi1) + int(sayi2)
print("Toplamlari: " + str(toplam))
